name: scan with zap
on: [push]

jobs:
  zap_scan:
    runs-on: abdelhadioubella/exam
    name: Scan the webapplication
    steps:     
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://178pkvmk25nc.share.zrok.io/#/'
          #rules_file_name: '.zap/rules.tsv'
          #cmd_options: '-a'
          #docker_name: 'owasp/zap2docker-stable'
          #rules_file_name: '.zap/rules.tsv'
          #cmd_options: 'a'
   
